# Numpy

## References: 

- [Datacamp - Numpy](https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=1)

- [Numpy](https://numpy.org/doc/stable/user/whatisnumpy.html)


## Overview

NumPy is a popular Python library used for numerical computing, which provides efficient data structures for multi-dimensional arrays and matrices, as well as a variety of mathematical functions for performing operations on these arrays.

## Arrays:

The most fundamental data structure in NumPy is the `ndarray`, which is a multi-dimensional array. NumPy arrays are similar to Python lists, but they are more efficient for numerical computations and can have any number of dimensions.

Example:


In [3]:
import numpy as np

# Create a 1D array
a = np.array([1, 2, 3])

# Create a 2D array
b = np.array([[1, 2], [3, 4], [5, 6]])

## Indexing and slicing: 

NumPy arrays can be indexed and sliced in a similar way to Python lists. You can access individual elements or subsets of an array by specifying the indices or slices you want.

Example:

In [4]:
import numpy as np

# Create a 2D array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexing
print(a[0, 0])  # Output: 1
print(a[1, 2])  # Output: 6

# Slicing
print(a[:, 1])  # Output: [2 5 8]
print(a[1:, :2])  # Output: [[4 5] [7 8]]


1
6
[2 5 8]
[[4 5]
 [7 8]]


## Vectorized operations: 

NumPy provides a variety of mathematical functions that can be applied to entire arrays or subsets of arrays, without the need for loops. This is known as vectorization, and it is a powerful feature of NumPy that makes it much faster and more efficient than traditional Python lists.

Example:

In [5]:
import numpy as np

# Create a 1D array
a = np.array([1, 2, 3])

# Vectorized operations
print(a + 2)  # Output: [3 4 5]
print(a * 3)  # Output: [3 6 9]


[3 4 5]
[3 6 9]


## [Broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html#):

NumPy arrays can be broadcast to perform operations on arrays with different shapes or dimensions. This allows you to perform complex calculations on arrays of different sizes, without the need for complex loops or iteration.

Example:

In [10]:
import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])